name: AtlasUtils
version: '${project.version}'
main: net.atlaspvp.atlasutils.AtlasUtils
api-version: 1.13
authors: [ jesus_is_hot ]
description: Plugin with helpful tools for factions, made to be used beside atlas spigot.
website: atlaspvp.net

depend:
  [ ProtocolLib ]

commands:
  fps:
    decription: Open the FPS GUI
    usage: /<command>
    aliases: [ fpssettings, fpsgui ]
    permission: atlasutils.fps
  tnttoggle:
    decription: Toggle TNT Visibility
    usage: /<command>
    aliases: [ toggletnt ]
    permission: atlasutils.tnttoggle
  sandtoggle:
    decription: Toggle FallingBlock Visibility
    usage: /<command>
    aliases: [ togglesand, fallingtoggle, fallingblocktoggle, togglefalling, togglefallingblock ]
    permission: atlasutils.sandtoggle
  explosiontoggle:
    decription: Toggle Explosion Visibility
    usage: /<command>
    aliases: [ particletoggle, etoggle, explosiont, particlet, ptoggle, toggleparticles, toggleexplosions ]
    permission: atlasutils.explosiontoggle
  maxfps:
    decription: Toggle All FPS Settings
    usage: /<command>
    aliases: [ toggleall, alltoggle, fpsmax ]
    permission: atlasutils.maxfps

  reload:
    decription: Reload AtlasUtils Config
    usage: /<command>
    aliases: [ aureload, reloadau, atlasutilsreload, reloadatlasutils ]
    permission: atlasutils.reload